fragment BaseStripeSubscription on StripeSubscription {
  id
  created
  metadata
  status
  quantity
  metadata
  cancelAt
  cancelAtPeriodEnd
  canceledAt
  currentPeriodEnd
  currentPeriodStart
  endedAt
  stripePrice {
    ...BaseStripePrice
  }

  upcomingQuantity
  upcomingStartDate
  upcomingStripePrice {
    ...BaseStripePrice
  }
}
