query CurrentProjectSettings($projectId: String) {
  currentProject(projectId: $projectId) {
    ...BaseProjcet
    subscriptionPlan
    users {
      id
      createdAt
      role
      user {
        id
        createdAt
        name
        image
        email
      }
    }
    userInvites {
      id
      createdAt
      role
      email
    }
    stripePaymentMethods {
      ...BasePaymenthMethod
    }
    stripeInvoices {
      ...BaseStripeInvoice
    }
  }
}