query ProjectSettings($projectId: String) {
  project(projectId: $projectId) {
    ...BaseProjcet
    users {
      id
      createdAt
      role
      user {
        id
        createdAt
        name
        image
        email
      }
    }
    userInvites {
      id
      createdAt
      role
      email
    }
    stripeSubscriptions {
      ...BaseStripeSubscription
    }
    stripePaymentMethods {
      ...BaseStripePaymenthMethod
    }
    stripeInvoices {
      ...BaseStripeInvoice
    }
  }
}