query ProjectInvoices($projectId: String, $invoicesWhere: ProjectStripeInvoicesWhereInput, $invoicesOrderBy: [ProjectStripeInvoicesOrderByInput!]) {
  project(projectId: $projectId) {
    id
    stripeInvoices(where: $invoicesWhere, orderBy: $invoicesOrderBy) {
      ...BaseStripeInvoice
    }
  }
}