query ProjectSettings($projectId: String, $invoicesWhere: ProjectStripeInvoicesWhereInput, $invoicesOrderBy: [ProjectStripeInvoicesOrderByInput!]) {
  project(projectId: $projectId) {
    ...BaseProjcet
    users {
      id
      createdAt
      role
      user {
        id
        createdAt
        name
        image
        email
      }
    }
    userInvites {
      id
      createdAt
      role
      email
    }
    stripeSubscriptions(where: { status: { equals: ACTIVE } }) {
      ...BaseStripeSubscription
    }
    stripePaymentMethods {
      ...BaseStripePaymenthMethod
    }
    stripeInvoices(where: $invoicesWhere, orderBy: $invoicesOrderBy) {
      ...BaseStripeInvoice
    }
    purchasedProducts {
      ...BasePurchasedProduct
    }
  }
}